--- # Ansible Role [Nginx]: tasks.main (Axel Pardemann <axelitus@GitHub>)
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_distribution }}/install_nginx.yml"
- include: "{{ ansible_distribution }}/create_ssl_cert.yml"
- include: "{{ ansible_distribution }}/reconfigure_nginx.yml"