--- # Ansible Role [Nginx]: tasks.ubuntu.create_ssl_cert (Axel Pardemann <axelitus@GitHub>)
- name: Check if OpenSSL exists
  command: dpkg-query -l openssl
  register: openssl_exists
  failed_when: openssl_exists.rc > 1
  changed_when: no

- name: Create SSL folders
  file:
    path: "{{ axelitus_nginx_ssl_path }}"
    owner: "root"
    group: "root"
    mode: 0755
    state: directory
  when: openssl_exists|succeeded
  register: ssl_create_folder

- name: Create SSL Key
  shell: openssl genrsa -out "{{ axelitus_nginx_ssl_cert_key }}" 2048
  when: ssl_create_folder|succeeded
  register: ssl_create_key

- name: Create SSL Certificate Request
  shell: openssl req -new -key "{{ axelitus_nginx_ssl_cert_key }}" -out "{{ axelitus_nginx_ssl_cert_csr }}" -subj "/C={{ axelitus_nginx_ssl_cert_csr_country }}/ST={{ axelitus_nginx_ssl_cert_csr_state }}/L={{ axelitus_nginx_ssl_cert_csr_city }}/O={{ axelitus_nginx_ssl_cert_csr_org }}/OU={{ axelitus_nginx_ssl_cert_csr_ou }}/CN={{ axelitus_nginx_ssl_cert_csr_cn }}"
  when: ssl_create_key|succeeded
  register: ssl_create_csr

- name: Create SSL Certificate
  shell: openssl x509 -req -days 365 -in "{{ axelitus_nginx_ssl_cert_csr }}" -signkey "{{ axelitus_nginx_ssl_cert_key }}" -out "{{ axelitus_nginx_ssl_cert_crt }}"
  when: ssl_create_csr|succeeded
  register: ssl_create_crt